# Generated by Django 2.2 on 2019-04-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomecompleto', models.CharField(max_length=60, verbose_name='Nome Completo')),
                ('datadenascimento', models.DateTimeField(verbose_name='Data Nascimento')),
                ('etinia', models.CharField(max_length=30, verbose_name='Etinia')),
                ('religiao', models.CharField(max_length=60, verbose_name='Religião')),
                ('filhosmaiores', models.IntegerField(verbose_name='Filhos Maiores')),
                ('filhosmenores', models.IntegerField(verbose_name='Filhos Menores')),
                ('graudeinstrucao', models.CharField(max_length=60, verbose_name='Grau de Instrução')),
                ('cep', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=60)),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('bairro', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=40)),
                ('uf', models.CharField(max_length=2)),
                ('ibge', models.CharField(max_length=8)),
                ('telefone', models.CharField(blank=True, max_length=16, null=True)),
                ('hipotesedig', models.CharField(max_length=100, verbose_name='Hipótese Diagnóstica:')),
                ('atemdimento', models.CharField(max_length=100, verbose_name='Atendimento:')),
                ('retornoum', models.CharField(max_length=100, verbose_name='Retorno 1:')),
                ('retornodois', models.CharField(max_length=100, verbose_name='Retorno 2:')),
                ('obs', models.CharField(max_length=100, verbose_name='Obs:')),
            ],
            options={
                'verbose_name': 'Cadastro',
                'verbose_name_plural': 'Cadastro',
                'ordering': ['id'],
            },
        ),
    ]
