# Generated by Django 2.2 on 2019-04-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190428_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='filhossn',
            field=models.CharField(choices=[('-----', '-----'), ('SIM', 'Sim'), ('NÃO', 'Não')], default='-----', max_length=9),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='estadocivil',
            field=models.CharField(choices=[('-----', '-----'), ('SOLTEIRO(A)', 'Solteiro(a)'), ('CASADO(A)', 'Casado(a)')], default='-----', max_length=9),
        ),
    ]
