# Generated by Django 2.2 on 2019-04-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190429_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='profissao',
            field=models.CharField(default=1, max_length=60, verbose_name='Profissao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='filhos',
            field=models.CharField(choices=[('NÃO', 'Não'), ('1', '1'), ('2', '2'), ('3', '3'), ('4 OU MAIS', '4 ou mais')], default='NÃO', max_length=9, verbose_name='Qnts'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='filhosmaiores',
            field=models.IntegerField(verbose_name='Filhos Maiores de Idade'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='filhosmenores',
            field=models.IntegerField(verbose_name='Filhos Menores de Idade'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='filhossn',
            field=models.CharField(choices=[('-----', '-----'), ('SIM', 'Sim'), ('NÃO', 'Não')], default='-----', max_length=9, verbose_name='Filhos?'),
        ),
    ]
