# Generated by Django 2.2 on 2019-04-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190429_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='estadocivil',
            field=models.CharField(choices=[('-----', '-----'), ('SOLTEIRO(A)', 'Solteiro(a)'), ('CASADO(A)', 'Casado(a)')], default='-----', max_length=11),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='ibge',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
