# Generated by Django 2.2 on 2019-05-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_cadastro_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='atemdimento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atendimento:'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='bairro',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cidade',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='datadenascimento',
            field=models.DateTimeField(blank=True, max_length=10, null=True, verbose_name='Data Nascimento'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='etinia',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Etinia'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='filhosmaiores',
            field=models.IntegerField(blank=True, null=True, verbose_name='Filhos Maiores de Idade'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='filhosmenores',
            field=models.IntegerField(blank=True, null=True, verbose_name='Filhos Menores de Idade'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='graudeinstrucao',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Grau de Instrução'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='hipotesedig',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hipótese Diagnóstica:'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Nº Ficha'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='obs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Obs:'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='profissao',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Profissao'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='religiao',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Religião'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='retornodois',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Retorno 2:'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='retornoum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Retorno 1:'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='rua',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='sexo',
            field=models.CharField(choices=[('----', '----'), ('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], default='----', max_length=9, verbose_name='Sexo:'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='telefone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
