# Generated by Django 2.2 on 2019-05-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190510_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='numeroficha',
            field=models.IntegerField(default=1, verbose_name='Nº Ficha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
